### ISSUE TITLE
AWS Build failed for Zynq

### ISSUE THREAD

**Issue by ohkawatks** [yhmtmt/aws#1]
I am following the procedure of "Building aws" in https://github.com/yhmtmt/aws.
The build environment is petalinux-2014.2. (petalinux-build works fine)

After cloning the following repositories,

> git clone https://github.com/yhmtmt/aws.git
> git clone https://github.com/yhmtmt/CmdAppBase.git

The make command fails with the following error.

> $ make "ZYNQ=y"
> Makefile:70: /data/Xilinx/petalinux/petalinux-v2014.2-final/software/petalinux-dist/tools/user-commons.mk: No such file or directory
> make: **\* No rule to make target `/data/Xilinx/petalinux/petalinux-v2014.2-final/software/petalinux-dist/tools/user-commons.mk'.  Stop.

Should I install something else besides petalinux-2014.2?
There is no "/data/Xilinx/petalinux/petalinux-v2014.2-final/software/" directory.

**Comment by yhmtmt** [comment]
sorry for the inconvenience.
This makefile was only tested on v2013.04.
In v2014.2, we still have some troubles in building petalinux kernel. So we
have not moved yet.

2014-12-02 7:21 GMT+09:00 Takeshi Ohkawa notifications@github.com:

**Comment by ohkawatks** [comment]
Thank you for your quick reply. I am going to try it using v2013.04. (Its download from Xilinx takes too long time...)

**Comment by yhmtmt** [comment]
Actually the "include" line is merely configuring the cross compile
environment.
Modifying the environment variable would be an immediate solution.

2014-12-02 9:31 GMT+09:00 Takeshi Ohkawa notifications@github.com:

**Comment by ohkawatks** [comment]
Thank you for putting useful information. 
Anyway, I have installed  v2013.04 already and trying on... 

One thing I should report is that I had to change the file name "PvApi.h" into "PvAPI.h".

**Comment by yhmtmt** [comment]
Thanks.
Corresponding lines in f_avt_cam.h is modified.

2014-12-02 12:43 GMT+09:00 Takeshi Ohkawa notifications@github.com:

**Comment by ohkawatks** [comment]
Now the build passed the compile and fails at linking. It seems the library of opencv-2.4.9 built for arm has some problem. Is there any special cmake parameter necessary for building opencv-2.4.9?

[ohkawa@primo aws]$ make
...
arm-xilinx-linux-gnueabi-g++ -std=gnu++0x -D_arm -D_LINUX  -DAVT_CAM -I/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/opencv/include  -I/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/PvAPI/include   -g      command.o c_aws.o aws.o  /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_base.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_nmea.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_cam.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_camcalib.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_imgshk.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_misc.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_shioji.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_ship_detector.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_stabilizer.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_com.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_uvc_cam.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/filter/f_avt_cam.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/channel/ch_base.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/util/c_clock.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/util/c_imgalign.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/util/c_nmeadec.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/util/c_ship.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/util/coord.o /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/util/util.o -o aws -L/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/opencv/arm/lib -lpthread -lopencv_core -lopencv_contrib -lopencv_features2d -lopencv_imgproc -lopencv_imgproc -lopencv_calib3d -lopencv_ml  -lopencv_flann -lopencv_video -lopencv_legacy -lopencv_nonfree -lopencv_objdetect -lopencv_highgui -lopencv_photo -lopencv_gpu -L/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/cminpack/LINUX/arm -lcminpack -L/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/PvAPI/bin/arm -lPvAPI
/data/Xilinx/petalinux/petalinux-v2014.2-final/tools/linux-i386/arm-xilinx-linux-gnueabi/bin/../lib/gcc/arm-xilinx-linux-gnueabi/4.8.1/../../../../arm-xilinx-linux-gnueabi/bin/ld: warning: libopencv_ocl.so.2.4, needed by /home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/opencv/arm/lib/libopencv_contrib.so, not found (try using -rpath or -rpath-link)
/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/opencv/arm/lib/libopencv_nonfree.so: undefined reference to `cv::ocl::oclMat::setTo(cv::Scalar_<double> const&, cv::ocl::oclMat const&)'
/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/opencv/arm/lib/libopencv_nonfree.so: undefined reference to`cv::ocl::oclMat::release()'
 ....
collect2: error: ld returned 1 exit status
make[1]: **\* [aws] Error 1
make[1]: Leaving directory `/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws'
make: **\* [all] Error 2
[ohkawa@primo aws]$

It's strange. I have libopencv_ocl.so.2.4, but the ld says it is not found?

[ohkawa@primo lib]$ pwd
/home/ohkawa/Avnet-Digilent-ZedBoard-2014.2-001/components/apps/aws/opencv/arm/lib
[ohkawa@primo lib]$ ls
libopencv_calib3d.so           libopencv_highgui.so          libopencv_ocl.so
libopencv_calib3d.so.2.4       libopencv_highgui.so.2.4      libopencv_ocl.so.2.4
libopencv_calib3d.so.2.4.9     libopencv_highgui.so.2.4.9    libopencv_ocl.so.2.4.9
libopencv_contrib.so           libopencv_imgproc.so          libopencv_photo.so
libopencv_contrib.so.2.4       libopencv_imgproc.so.2.4      libopencv_photo.so.2.4
libopencv_contrib.so.2.4.9     libopencv_imgproc.so.2.4.9    libopencv_photo.so.2.4.9
libopencv_core.so              libopencv_legacy.so           libopencv_stitching.so
libopencv_core.so.2.4          libopencv_legacy.so.2.4       libopencv_stitching.so.2.4
libopencv_core.so.2.4.9        libopencv_legacy.so.2.4.9     libopencv_stitching.so.2.4.9
libopencv_features2d.so        libopencv_ml.so               libopencv_superres.so
libopencv_features2d.so.2.4    libopencv_ml.so.2.4           libopencv_superres.so.2.4
libopencv_features2d.so.2.4.9  libopencv_ml.so.2.4.9         libopencv_superres.so.2.4.9
libopencv_flann.so             libopencv_nonfree.so          libopencv_video.so
libopencv_flann.so.2.4         libopencv_nonfree.so.2.4      libopencv_video.so.2.4
libopencv_flann.so.2.4.9       libopencv_nonfree.so.2.4.9    libopencv_video.so.2.4.9
libopencv_gpu.so               libopencv_objdetect.so        libopencv_videostab.so
libopencv_gpu.so.2.4           libopencv_objdetect.so.2.4    libopencv_videostab.so.2.4
libopencv_gpu.so.2.4.9         libopencv_objdetect.so.2.4.9  libopencv_videostab.so.2.4.9
[ohkawa@primo lib]$

**Comment by yhmtmt** [comment]
Maybe it is caused by OpenCL support. I disabled OpenCL support because we
do not use it.
Rebuilding OpenCV without OpenCL support or  Inserting "-lopencv_ocl"
 would remove the problem.

**Comment by ohkawatks** [comment]
Thanks for your advice. I will try again with the OpenCL support disabled.

**Comment by ohkawatks** [comment]
During building OpenCV with OpenCL support disabled, I tried "-lopencv_ocl".
Then the build succeeded! I will try the executable binary on the zedboard...
