### ISSUE TITLE
AWS compilation error in f_avt_cam.cpp

### ISSUE THREAD

**Issue by ohkawatks** [yhmtmt/aws#3]
Compilation failed at the commit https://github.com/yhmtmt/aws/commit/0b00b15c6108f371a4a72cfa44ebca908f407037

>  [ohkawa@primo aws]$ make
> 
> arm-xilinx-linux-gnueabi-g++ -std=gnu++0x -D_arm -D_LINUX  -DAVT_CAM -I/usr/local/include  -I/home/ohkawa/work/aws/opencv/include  -I/home/ohkawa/work/aws/PvAPI/include   -g    -c f_avt_cam.cpp -o f_avt_cam.o
> cc1plus: warning: include location "/usr/local/include" is unsafe for cross-compilation [-Wpoison-system-directories]
> f_avt_cam.cpp: In member function 'virtual bool f_avt_cam::init_run()':
> f_avt_cam.cpp:410:1: error: jump to label 'cam_close' [-fpermissive]
>  cam_close:
>  ^
> f_avt_cam.cpp:331:8: error:   from here [-fpermissive]
>    goto cam_close;
>         ^
> f_avt_cam.cpp:335:6: error:   crosses initialization of 'int m_size_buf'
>   int m_size_buf = 0;
>       ^
> make[2]: **\* [f_avt_cam.o] Error 1
> make[2]: Leaving directory `/home/ohkawa/work/aws/filter'
> make[1]: *** [filter] Error 2
> make[1]: Leaving directory`/home/ohkawa/work/aws'
> make: **\* [all] Error 2
> [ohkawa@primo aws]$

This error is caused by the goto statement skipping the initialization of m_size_buf.
(Maybe compiler dependent error only for arm cross compiliation)
Here is a candidate for modification. Thanks

> diff --git a/filter/f_avt_cam.cpp b/filter/f_avt_cam.cpp
> index d3359b0..2c2e046 100755
> --- a/filter/f_avt_cam.cpp
> +++ b/filter/f_avt_cam.cpp
> @@ -298,6 +298,8 @@ bool f_avt_cam::config_param_dynamic()
> 
>  bool f_avt_cam::init_run()
>  {
> - ```
>     int m_size_buf = 0;
>   ```
>   
>   +
>       if(!m_chout.size()){
>               f_base::send_err(this, **FILE**, **LINE**, FERR_AVT_CAM_CH);
>               return false;
>   @@ -332,7 +334,6 @@ bool f_avt_cam::init_run()
>       }
>   
>   ```
>   // getting frame size sent from camera
>   ```
> - ```
>     int m_size_buf = 0;
>   err = PvAttrUint32Get(m_hcam, "TotalBytesPerFrame", (tPvUint32*)&m_size_buf);
>   
>   if(err != ePvErrSuccess){
>   ```

**Comment by yhmtmt** [comment]
Thanks.
I did not know the behavior of the compiler.
Microsoft c++ compiler does not blame  it.

The modified version was uploaded.

2014-12-04 4:08 GMT+09:00 Takeshi Ohkawa notifications@github.com:
