### ISSUE TITLE
AWS remote operation doesn't work

### ISSUE THREAD

**Issue by ohkawatks** [yhmtmt/aws#4]
Hello, from the version yesterday, remote operation doesn't work. 
The first line of the sample filter worked, however, it doesn't start. I saw some modification on rcmd recent days.
Could you give me some hints to solve the problem?

```
root@Avnet-Digilent-ZedBoard-2014_2-aws-uu-20141216:~/aws# ./aws
aws Ver.0.10 (built Dec 25 2014 10:57:32)
Copyright (c) 2014 Yohei Matsumoto All Rights Reserved
matumoto (at) kaiyodai.ac.jp
aws>filter smpl added.
```

**Comment by yhmtmt** [comment]
I guess that the commands have not been updated.
The binaries of the commands (filter, channel, fset, fget ... etc)  are to
be updated.

2014-12-25 10:58 GMT+09:00 Takeshi Ohkawa notifications@github.com:
