### ISSUE TITLE
AWS build failed: minor fixes for the new year updates.

### ISSUE THREAD

**Issue by ohkawatks** [yhmtmt/aws#5]
A happy new year! After I pulled the latest source form the repository, I have faced to building failure and solved them. I would like to propose two minor fixes for the new year updates.

- 1. missing #include

The "f_sample.h" is necessary to be included. 
```
diff --git a/factory.cpp b/factory.cpp
index b4246a1..4312a63 100755
--- a/factory.cpp
+++ b/factory.cpp
@@ -97,6 +97,7 @@ void ch_base::register_factory()
 // your filter's header file here. 
 #include "filter/f_base.h"
 #include "filter/f_misc.h"
+#include "filter/f_sample.h"
 #include "filter/f_stabilizer.h"
 #include "filter/f_cam.h"
 #ifdef AVT_CAM
diff --git a/filter/f_uvc_cam.cpp b/filter/f_uvc_cam.cpp
index 012ef8e..2644114 100755
--- a/filter/f_uvc_cam.cpp
+++ b/filter/f_uvc_cam.cpp
@@ -52,7 +52,7 @@ using namespace cv;
 #include "../util/aws_thread.h"
 #include "../util/c_clock.h"
 #include "../util/util.h"
-#include "../channel.h"
+//#include "../channel.h"
 #include "f_base.h"
 #include "f_cam.h"
```

- 2. missing "split_cmd_tok" function

The two files is modified to restore the commented "split_cmd_tok" function.
(I think they are under modification.)

 - rcmd/aws_cmd.cpp
 - rcmd/c_aws_cmd.cpp

Good luck!

**Comment by yhmtmt** [comment]
Sorry for the inconvenience. 
These were missing update of the files.
I pushed new factory.cpp, filter/f_uvc_cam.cpp and rcmd/Makefile .

Thanks.
