### ISSUE TITLE
tcp broblem in linux.

### ISSUE THREAD

**Issue by nkshr** [yhmtmt/aws#9]
When I rerun aws, I must be waited because of aws's tcp.It is too late. Could you change tcp to udp.

**Comment by yhmtmt** [comment]
You mean that the aws cannot run immediately after killing aws because the tcp's TIME_WAIT disturbs reusing the same socket.

The code is revised to use reuse option, and the problem would no longer happen.

**Comment by nkshr** [comment]
Thank you very much!!
It is good result which I hope.
